### ISSUE TITLE
accessing OpenAI_API_key and initialising database

### ISSUE THREAD

**Issue by Aditya-139** [arjitvermaco/DbDost#1]
hello sir, i recently watched your insta reel mentioning this specific project. upon keen interest i started to work on it and im learning from it.

please explain the process to get the api keys and setting the database.

contact : makkenaaditya139@gmail.com

**Comment by divyesh-thadani** [comment]
Hello @Aditya-139 can you please explain how we can access it currently, I am trying to access app.py using command python app.py but get error of the database.

**Comment by Aditya-139** [comment]
First setup data base and use u-id and password in the required areas in
code.
Secondly I'm sending a video tutorial for api key.

https://youtube.com/shorts/teGspojqOAc?si=-Kv7OFVrxm_l-R94


If any further quires please let me know

**Comment by divyesh-thadani** [comment]
@Aditya-139 
Sorry, totally newbie here I don't have any experience with the sqlite can you explain how I can get u-id and password?
I have already API key with me and have supplied model to be Gpt 4o mini.

**Comment by Aditya-139** [comment]
Surely,  I'm having exams right now. If you can wait till 23 then we can
arrange a call so that you can learn about the whole project. If works then
mail me at ***@***.***
I will reply on 23 with credentials to connect with you.

**Comment by divyesh-thadani** [comment]
@Aditya-139 Sure no problem.
